---
applications:
- guillotina_dbusers
databases:
- db:
    storage: postgresql
    transaction_strategy: resolve
    dsn:
      scheme: postgres
      dbname: guillotina
      user: postgres
      host: localhost
      password: ''
      port: 5432
    pool_size: 40
    read_only: false
host: 0.0.0.0
port: 8080
root_user:
  password: root
